[package]
name = "olhar_ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlib = "0.5.2"
dlib-face-recognition = "0.3.2"
opencv = "0.88.8"
